
apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/films
    context: .
    docker:
      dockerfile: manifests/Dockerfile
  local:
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - manifests/kubernetes/films-deployment.yaml
    - manifests/kubernetes/films-service.yaml
    - manifests/kubernetes/roach-ui-claim0-persistentvolumeclaim.yaml
    - manifests/kubernetes/roach-ui-deployment.yaml
    - manifests/kubernetes/roach-ui-service.yaml
